### ISSUE TITLE
Site (and public server) seems down

### ISSUE THREAD

**Issue by cristiano-belloni** [patchbay-pub/patchbay.pub#6]
It seems that the site (and the public server, as the site is served from it) is currently down at the moment: https://downforeveryoneorjustme.com/patchbay.pub

**Comment by anderspitman** [comment]
Hey @cristiano-belloni, thanks for the heads up. It's back now.

**Comment by cristiano-belloni** [comment]
@anderspitman it seems down again

**Comment by anderspitman** [comment]
Hey @cristiano-belloni, sorry for the delay. There's something up with it where it keeps dying. I've been restarting it manually, but it's been down a lot the past few weeks.

I just changed it to run as a systemd service, which should be auto-restarted now. Hopefully this will resolve the issue.

**Comment by NotNite** [comment]
Unfortunately seems to be down again.

**Comment by anderspitman** [comment]
@NotNite I put some more monitoring in place. Hopefully fixed this time...
