### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by polettix** [patchbay-pub/patchbay.pub#7]
Hi! Just to let you know that the site is down since some weeks now.

**Comment by anderspitman** [comment]
Thanks @polettix. Should be back up now.

**Comment by polettix** [comment]
Brilliant, thanks!

**Comment by BlackGlory** [comment]
@anderspitman Site is down again, it is recommended to use [UptimeRobot](https://uptimerobot.com/).

**Comment by anderspitman** [comment]
Good suggestion @BlackGlory. I signed up for an account but sadly the free tier only supports HEAD requests, which patchbay does not support. Generally patchbay doesn't get enough traffic to go down very often, but it does seem to be happening more. If it continues I'll have to find a more permanent solution.
