### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by SebastianAigner** [patchbay-pub/patchbay.pub#8]
Hiya! I greatly enjoyed building a small prototype for a personal app a few years ago with patchbay. I just checked back on https://patchbay.pub/index.html and noticed it's down, so I figured I'd draw attention to it. Thanks for building this in the first place, it's a very inspiring project!

**Comment by anderspitman** [comment]
Super long delay but finally fixed this. Thanks @SebastianAigner!
